### ISSUE TITLE
Rewriters not working as expected

### ISSUE THREAD

**Issue by corbanb** [R35007/Mock-Server#2]
@R35007 - Hey thanks so much for the work here. Really love everything you are building especially the work on the homepage addition compared to other mocking tools. 

Any chance you can shed some light on why my rewriters aren't showing up? I have experienced them showing sometimes and not others when I restart the server. Thoughts? 

```js
// server.js

const { MockServer } = require("@r35007/mock-server");
const db = require("./data/db");

const quiet = false; // Set to true to suppress console logs
const log = true; // Set to true to see logs. If quiet is false the we cant see the setter logs.
const port = 3000; // Set Port to 0 to pick a random available port. default: 3000
const host = "localhost"; // Set empty string to set your Local Ip Address
const config = { root: __dirname, port, host, quiet };
const mockServer = MockServer.Create(config);

const app = mockServer.app;

// Sets global injectors, middlewares, store and rewriters
mockServer.setData(
  {
    injectors: "./injectors.json",
    middlewares: "./middlewares.js",
    store: "./store.json",
    rewriters: "./rewriters.json",
  },
  { log }
); // pass mockServer instance to use it in middleware.js method

// Make sure to use this at first, before all the resources
const rewriter = mockServer.rewriter();

// Returns the default middlewares
const defaultsMiddlewares = mockServer.defaults();

// add your authorization logic here
const isAuthorized = (_req) => true;

// Custom Middleware
app.use((req, res, next) => {
  if (isAuthorized(req)) return next(); // continue to Mock Server router
  res.sendStatus(401);
});

// Creates resources and returns the express router
const resources = mockServer.resources(db, { log });

// Create the Mock Server Home Page
const homePage = mockServer.homePage({ log });

app.use(rewriter);
app.use(defaultsMiddlewares);
app.use(resources.router);
app.use(homePage);
app.use(mockServer.pageNotFound); // Middleware to return `Page Not Found` as response if the route doesn't match
app.use(mockServer.errorHandler); // Default Error Handler

mockServer.startServer();
// mockServer.startServer(port, host); // can also set port and host here

```

```js
// rewriters.json
{
  "/api/*": "/$1"
}
```

**Comment by R35007** [comment]
Hi. @corbanb ,

Sorry for the inconvenience. From the version 11.0.0 we cant able to set the Db and Rewriters directly using setter methods.
`mockServer.setDb`, `mockServer.setRewriters` and `mockServer.setData({ rewriters, db })` are removed and will not work.

From version 11.0.0 we need to directly give the path or object for rewriters and db to the respective method.

Please use the below code if your mock server version is equal or above v11.0.0.

```js
// server.js

const { MockServer } = require("@r35007/mock-server");
const db = require("./data/db");

const quiet = false; // Set to true to suppress console logs
const log = true; // Set to true to see logs. If quiet is false the we cant see the setter logs.
const port = 3000; // Set Port to 0 to pick a random available port. default: 3000
const host = "localhost"; // Set empty string to set your Local Ip Address
const config = { root: __dirname, port, host, quiet };
const mockServer = MockServer.Create(config);

const app = mockServer.app;

// Sets global injectors, middlewares and store
mockServer.setData(
  {
    injectors: "./injectors.json",
    middlewares: "./middlewares.js",
    store: "./store.json"
  },
  { log }
); // pass mockServer instance to use it in middleware.js method

// Make sure to use this at first, before all the resources
const rewriter = mockServer.rewriter("./rewriters.json"); // Give Rewriters path or object here

// Returns the default middlewares
const defaultsMiddlewares = mockServer.defaults();

// add your authorization logic here
const isAuthorized = (_req) => true;

// Custom Middleware
app.use((req, res, next) => {
  if (isAuthorized(req)) return next(); // continue to Mock Server router
  res.sendStatus(401);
});

// Creates resources and returns the express router
const resources = mockServer.resources(db, { log });

// Create the Mock Server Home Page
const homePage = mockServer.homePage({ log });

app.use(rewriter);
app.use(defaultsMiddlewares);
app.use(resources.router);
app.use(homePage);
app.use(mockServer.pageNotFound); // Middleware to return `Page Not Found` as response if the route doesn't match
app.use(mockServer.errorHandler); // Default Error Handler

mockServer.startServer();
// mockServer.startServer(port, host); // can also set port and host here
```

**Comment by R35007** [comment]
Please also check the `VS Code Extension` for this `Mock Server`. Its Easy to setup with low code.
[https://marketplace.visualstudio.com/items?itemName=Thinker.mock-server](https://marketplace.visualstudio.com/items?itemName=Thinker.mock-server)

![Mock Server VSCode Extension](https://github.com/R35007/Mock-Server/blob/main/src/img/VSCode_Extension.gif?raw=true)

Thanks for the Love and Support 🙂

**Comment by corbanb** [comment]
@R35007 - thanks so much for the info. I copied this server.js code over to my repo but its still not showing the route rewriters on the homepage nor are they usable. 

Feel free to take a look here. 

FWIW - I am using commonjs to build my db which seems to be working fine. I am also running the mock server outside of the vscode plugin as I was running into issues with that. 

The strange thing here is IF I now use the VSCODE plugin it works with the rewriters but not running stand-alone. Ideally, I could use the scripts outside of the vscode plugin to deploy this. But not sure what's causing the difference. 

I could explain this further if need be as well. Thanks again! 

[mock-api-v.2.2.zip](https://github.com/R35007/Mock-Server/files/9939504/mock-api-v.2.2.zip)

**Comment by corbanb** [comment]
@R35007 - Good morning. Thanks so much for your reply. There are a few interesting things happening now. I'll try to outline the variances I am experiencing inside and outside of the vscode.

## Vscode Plugin Homepage
When running from Vscode
- NO Database
- Rewriters working
- Will run on other ports

![Screenshot 2022-11-04 at 9 09 22 AM](https://user-images.githubusercontent.com/140186/200009468-daa7c3f0-7d03-48a9-b10c-59dcc4fe8067.png)


## mock-server --watch ./data/db.js Homepage
When running from command line
- Database working
- NO Rewriters
- Will only start on 3000

![Screenshot 2022-11-04 at 9 10 38 AM](https://user-images.githubusercontent.com/140186/200009478-36cc6715-9510-4f1e-a09e-a228020b6518.png)

See the code here.

[mock-api-v.2.2.zip](https://github.com/R35007/Mock-Server/files/9939661/mock-api-v.2.2.zip)

**Comment by R35007** [comment]
@corbanb - Good Morning. Welcome and happy to help. Infact you are the first person to reach out me for help.

# Running Server.js file

Running Server.js file works perfectly fine.

# Running using VSCode Extension

Since your `Db` file is not directly at the root folder and also its  a js file we need to methion the db path in the vscode settings.
`settings.json`
```jsonc
"mock-server.settings.paths": {
    "db": "data/db.js"
  },
```
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/23217228/200014094-6b2ff00b-17ae-47c4-b02e-e62dd7f1fd4b.png">

# Running using CLI

As you have mentioned earlier, the command - `mock-server --watch ./data/db.js`.

Since you haven't added the rewriter path, it's not adding to the server. We need to specifically mention all the middlewares, store, rewriters, injectors, db path while running thru CLI.

Use the below command to run the server. 
```sh
mock-server --watch ./data/db.js --rw=./rewriters.json --st=./store.json --md=middlewares.js --P=4000
```

Alternatively we can also set all our cli config file as follows
`mock-server.json`
```json
{
  "port": 3000,
  "host": "localhost",
  "base": "",
  "id": "id",
  "dbMode": "mock",
  "static": "public",
  "reverse": false,
  "logger": true,
  "noCors": false,
  "noGzip": false,
  "readOnly": true,
  "bodyParser": true,
  "cookieParser": true,
  "quiet": false,
  "db": "./data/db.js",
  "rewriters": "./rewriters.json",
  "injectors": "./injectors.json",
  "store": "./store.json",
  "middlewares": "./middlewares.js"
}
```

Now run the CLI command as follows
```sh
mock-server
```
By default `mock-server` uses the config json file with the name `mock-server.json` from the root folder
For more CLI option please click [here](https://github.com/R35007/mock-server#cli-usage)

<img width="820" alt="image" src="https://user-images.githubusercontent.com/23217228/200017060-cf466a96-dde9-4e41-9ef6-b874e2164d0d.png">

<img width="1532" alt="image" src="https://user-images.githubusercontent.com/23217228/200017150-5554dc1e-3ee3-4278-baa8-3084acc90fa5.png">

**Comment by corbanb** [comment]
@R35007 - this is awesome. I'll take a look at this setup and get back to you if something doesn't work. Much appreciated for the help! 🙏 

Also, If I can find time I'll try to dig into the core with you more on how you could standardize this for both user types so users don't need to worry about where its being ran, or helping you with the docs. Your project is great and makes mocking REALLY nice. 

Thanks again for your time and help here. I'll let you know if I run into other troubles. 

BTW - I found this tool in the VSCode extensions. So its working for you to find users there!

**Comment by R35007** [comment]
@corbanb - Thanks. Looking forward to collab together. I am working at a [verizon](https://www.verizon.com/) organization as a frontend developer. Here I got a need for this tool so that I have made this package. In my organization more than 200+ members are using this package. Not sure how much its useful for other users. I made this tool inspiring from node package [json-server](https://www.npmjs.com/package/json-server).

Please let me know if it works fine so that I can close this issue 🙂

**Comment by corbanb** [comment]
@R35007 - I am going to close this issue and open 2 others to help focus on a few things. As this is no longer related to the rewriters. I have uncovered a few things I think you will find interesting and can shed some light on. More to come!
