### ISSUE TITLE
Not working "_AdvancedSearch" middlewares

### ISSUE THREAD

**Issue by sangheePark** [R35007/Mock-Server#4]
**ex) not working**

"/users": {
  "_config": true,
  "description": "The given fetch path will be relative to the root path given in config",
  "fetch": ".mock/data/users.json",
  "middlewares": ["_AdvancedSearch"]
},

**ex) working**
"/users": {
  "_config": true,
  "description": "The given fetch path will be relative to the root path given in config",
  "mock": [
	  {
		  "userId": 1,
		  "id": 1,
		  "title": "Lorem ipsum dolor sit.",
		  "body": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Est, dolorem."
	  },
	  {
		  "userId": 1,
		  "id": 2,
		  "title": "Lorem ipsum dolor sit.",
		  "body": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Est, dolorem."
	  }
  ],
  "middlewares": ["_AdvancedSearch"]
},

**Comment by R35007** [comment]
As per the Given examples

In example 1: fetch path is set to `.mock/data/users.json` -> This means that the `users.json` is under the folder `.mock`. Please make sure you have given the right folder path. Try to give fetch path to `./mock/data/users.json`

Ans still `/users/1` -> wont work in both the examples as route id parameter is not specified as a optional parameter as `/users/:id?`.

Hope this helps.

Thanks,
Siva.

**Comment by R35007** [comment]
@sangheePark Please update the package to `14.2.0`
```sh
npm install @r35007/mock-server@14.2.0
```
