### ISSUE TITLE
`db.json` is not served

### ISSUE THREAD

**Issue by BachiMjavanadze** [R35007/Mock-Server#6]
This is my fake server code (in the root of the project):
```
// db.json
{
  "todos": [
    {
      "id": "123",
      "title": "title 1",
      "description": "description 1",
      "status": "active"
    },
    {
      "id": "456",
      "title": "title 2",
      "description": "description 2",
      "status": "active"
    },
    {
      "id": "789",
      "title": "title 3",
      "description": "description 3",
      "status": "active"
    }
  ]
}

// .mock-server.config.json
{
  "port": 3005,
  "host": "localhost",
  "id": "id",
  "db": "./db.json"
}
```
I run server: `npx mock-server --watch db.json --config .mock-server.config.json`

and with JavaScript front-end try to make CRUD operations. It works but only in memory, `db.json` is not updated? what is the reason?

**Comment by R35007** [comment]
1. Yes, we dont update the db.josn. it just updated only in memory.
2. You can still download the updated db.json using /_db route.
3. There is a vscode extension for the mock server which makes it easier
for server setup and runi g the server. Please try the 'Mock Server'
extension from vscode of you use vscode for code editing.
